#DOCKER-COMPOSE-VERSION: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/fantastic-library
      SPRING_DATASOURCE_USERNAME: WS
      SPRING_DATASOURCE_PASSWORD: NVARLvsWS
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    # --- CORREÇÃO AQUI ---
    # Agora o backend espera o mysql-db ficar "saudável" antes de iniciar.
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    # --- CORREÇÃO AQUI ---
    # Adicionada uma verificação de saúde para saber quando o MySQL está pronto.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "NVARL"
      MYSQL_DATABASE: "fantastic-library"
      MYSQL_USER: "WS"
      MYSQL_PASSWORD: "NVARLvsWS"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:

