services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Configuração para MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/Biblioteca
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # Descomente abaixo e comente as linhas acima para usar H2
      # SPRING_H2_CONSOLE_ENABLED: 'true'
      # SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      # SPRING_DATASOURCE_USERNAME: sa
      # SPRING_DATASOURCE_PASSWORD: ''
      # SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect

  database:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: Biblioteca
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
